fix(github): Hopefully will work with Dockerfiles.

diff --git a/.github/workflows/github-docker-registry-push.yml b/.github/workflows/github-docker-registry-push.yml
--- a/.github/workflows/github-docker-registry-push.yml
+++ b/.github/workflows/github-docker-registry-push.yml
@@ -29,19 +29,22 @@ jobs:
 
       - name: Check for Dockerfile and context changes
         run: |
-          # Searches for a specific pattern in the input. The -E option enables extended regular expression syntax.
-          # The pattern "(^|/)Dockerfile($|/)|(^|/)context/" is looking for any line that contains either "Dockerfile"
-          # or "context" as a whole word, and either at the start of the line, at the end of the line, or surrounded by
-          # slashes. This should match any changes to Dockerfiles or context directories.
-          if [[ $(echo "${{ env.files }}" | grep -E "(^|/)Dockerfile($|/)|(^|/)context/") ]]; then
-            echo "Dockerfile or context directory has changed."
-            echo Changed files are 
-            echo "${{ env.files }}"
-          else
+          # Checks if any files in the specified environment variable env.files match the patterns for a Dockerfile or
+          # a context directory.
+          # If a match is found, it prints a message indicating the changed file and breaks the loop.  
+          # After the loop, it checks the exit status of the loop using $? .
+          # If the exit status is non-zero (indicating a match was found), it prints a message stating that there are
+          # no Dockerfile or context directory changes and lists the changed files. 
+          for file in ${{ env.files }}; do
+            if [[ $file =~ (^|/)Dockerfile($|/)|(^|/)context/ ]]; then
+              echo "Dockerfile or context directory has changed."
+              echo "Changed file: $file"
+              break
+          fi
+          done
+          if (( $? )); then
             echo "No Dockerfile or context directory changes. Skipping Docker image build and push steps."
-            echo changed files are 
-            echo "${{ env.files }}"   
-            exit 0
+            echo "Changed files: ${{ env.files }}"
           fi
 
       - name: Set up QEMU
